version: '2'
services:
  data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    volumes:
      - /usr/local/openvpn_as/etc
  server:
    privileged: true
    image: registry.monach.us/docker/openvpn-as
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: data
    volumes_from:
      - data
    {{- if eq .Values.ADMINPORT "true" }}
    ports:
      - ${vpn_port}:1194/udp
      - ${admin_port}:943/tcp
    {{- else }}
    ports:
      - ${vpn_port}:1194/udp
    {{ end }}
